CREATE TABLE VCREDORUG (
    COCREDOR     VARCHAR2(14),
    NOCREDOR     VARCHAR2(113),
    NUTELEFONE   VARCHAR2(15),
    EDCREDOR     VARCHAR2(55),
    COCEP        NUMBER,
    SGUF         VARCHAR2(2),
    NOMUNICIPIO  VARCHAR2(50),
    COUGSIAFI    NUMBER
);