CREATE TABLE VFUNCAO (
    COFUNCAO       NUMBER(2,0)     NOT NULL,
    NOFUNCAO       CHAR(50)        NOT NULL,
    TXDESCRICAO    VARCHAR2(250)   NOT NULL,
    INSTATUS       NUMBER(1,0)     NOT NULL,
    ULTALTERACAO   CHAR(26)        NOT NULL
);