CREATE TABLE VNOTAADICIONAL_AUTORIZACAO (
    COUO                   NUMBER(5,0)     NOT NULL,
    NOUO                   VARCHAR2(153),
    NUNA                   CHAR(11)        NOT NULL,
    MOV                    CHAR(1),
    PROGRAMA_TRABALHO      VARCHAR2(21),
    NOME_PT                CHAR(50)        NOT NULL,
    FONTE                  NUMBER(9,0),
    NATUREZA               NUMBER(6,0),
    IDUSO                  NUMBER(1,0)     NOT NULL,
    VALANCAMENTO           NUMBER(17,2),
    COTIPOCREDITO          NUMBER(4,0),
    NORMATIVO              VARCHAR2(18),
    SITUACAO_NA            VARCHAR2(19),
    NUNO                   CHAR(11),
    NUAC                   CHAR(11),
    PROCESSO               CHAR(24),
    SITUACAO_AC            VARCHAR2(16),
    NUINSTRUMLEGAL         VARCHAR2(100),
    DAINSTRUMLEGAL         DATE,
    NUDODF                 NUMBER(3,0),
    DADODF                 DATE,
    NAT_RECEITA            NUMBER(8,0),
    UO_RECEITA             NUMBER(5,0)
);