CREATE TABLE VPROGRAMA (
    COPROGRAMA     NUMBER(4,0),
    NOPROGRAMA     CHAR(50),
    TXDESCRICAO    VARCHAR2(250),
    INSTATUS       NUMBER(1,0),
    ULTALTERACAO   CHAR(26),
    TXOBJETIVO     VARCHAR2(500)
);