CREATE TABLE VPROJETO (
    COPROJETO       NUMBER,
    NOPROJETO       VARCHAR2(250),
    TXDESCRICAO     VARCHAR2(250),
    INSTATUS        NUMBER,
    ULTALTERACAO    VARCHAR2(26),
    INNOVO          NUMBER,
    COPRIORIDADE1   NUMBER,
    COPRIORIDADE2   NUMBER,
    COPRIORIDADE3   NUMBER,
    COPRIORIDADE4   NUMBER,
    COPRIORIDADE5   NUMBER,
    COTIPOACAO      NUMBER,
    COPRODUTO       NUMBER,
    CODETALHAMENTO  NUMBER
);