CREATE TABLE VPT (
    COFUNCAO       NUMBER(2,0)     NOT NULL,
    COSUBFUNCAO    NUMBER(3,0)     NOT NULL,
    COPROGRAMA     NUMBER(4,0)     NOT NULL,
    COPROJETO      NUMBER(4,0)     NOT NULL,
    COSUBTITULO    NUMBER(4,0)     NOT NULL,
    NOPT           CHAR(50)        NOT NULL,
    TXDESCRICAO    VARCHAR2(250)   NOT NULL,
    INSTATUS       NUMBER(1,0)     NOT NULL,
    ULTALTERACAO   CHAR(26)        NOT NULL
);