CREATE TABLE VSUBFUNCAO (
    COSUBFUNCAO   NUMBER(3,0)     NOT NULL,
    NOSUBFUNCAO   CHAR(50)        NOT NULL,
    TXDESCRICAO   VARCHAR2(250)   NOT NULL,
    INSTATUS      NUMBER(1,0)     NOT NULL,
    ULTALTERACAO  CHAR(26)        NOT NULL
);