CREATE TABLE VSUBTITULO (
    COPROJETO        NUMBER,
    COSUBTITULO      NUMBER,
    NOSUBTITULO      VARCHAR2(250),
    TXDESCRICAO      VARCHAR2(250),
    INSTATUS         NUMBER,
    ULTALTERACAO     VARCHAR2(26),
    COLOCALIZACAO    NUMBER,
    INNOVO           NUMBER,
    INLDO            NUMBER,
    COUO             NUMBER,
    PRIORIDADE_EX    NUMBER
);