CREATE TABLE VUNIDADEGESTORA (
    COUG                  NUMBER(6,0)     NOT NULL,
    NOUG                  CHAR(50)        NOT NULL,
    COORGAO               NUMBER(5,0)     NOT NULL,
    COUO                  NUMBER(5,0)     NOT NULL,
    INSITUACAO            CHAR(1)         NOT NULL,
    EDUG                  VARCHAR2(50)    NOT NULL,
    COCEP                 NUMBER(8,0)     NOT NULL,
    SGUFUG                CHAR(2)         NOT NULL,
    NOMUNICIPIO           CHAR(50)        NOT NULL,
    COUGAUDITORIA         NUMBER(6,0)     NOT NULL,
    COUGFINANCEIRA        NUMBER(6,0)     NOT NULL,
    COUGCONTABIL          NUMBER(6,0)     NOT NULL,
    COUGPOLO              NUMBER(6,0),
    NUCGC                 NUMBER(14,0),
    NUCPFORDENADOR        NUMBER(11,0)    NOT NULL,
    NOORDENADOR           CHAR(50)        NOT NULL,
    NUCPFGESTOR           NUMBER(11,0)    NOT NULL,
    NOGESTOR              CHAR(50)        NOT NULL,
    NUCPFASSINATURA       NUMBER(11,0)    NOT NULL,
    NOASSINATURA          CHAR(50)        NOT NULL,
    NUCPFCHEFESOF         NUMBER(11,0),
    NOCHEFESOF            CHAR(50),
    NUCPFGESTORADM        NUMBER(11,0),
    NOGESTORADM           CHAR(50),
    INSTATUS              NUMBER(1,0)     NOT NULL,
    ULTALTERACAO          CHAR(26)        NOT NULL,
    TXDESCRICAO           VARCHAR2(150),
    INESTATAL             CHAR(1),
    COAREA                NUMBER(1,0),
    INPERMITEDIGITACAO    CHAR(1),
    VATETO                NUMBER(17,2)
);